/*
  Warnings:

  - You are about to drop the column `flashcardgroup_id` on the `FlashCard` table. All the data in the column will be lost.
  - You are about to drop the column `userflashcardgroup_id` on the `UserFlashCard` table. All the data in the column will be lost.
  - You are about to drop the `FlashCardGroup` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `UserFlashCardGroup` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `flashcarddeck_id` to the `FlashCard` table without a default value. This is not possible if the table is not empty.
  - Added the required column `priority_num` to the `UserFlashCard` table without a default value. This is not possible if the table is not empty.
  - Added the required column `userflashcarddeck_id` to the `UserFlashCard` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE "FlashCard" DROP CONSTRAINT "FlashCard_flashcardgroup_id_fkey";

-- DropForeignKey
ALTER TABLE "UserFlashCard" DROP CONSTRAINT "UserFlashCard_userflashcardgroup_id_fkey";

-- DropForeignKey
ALTER TABLE "UserFlashCardGroup" DROP CONSTRAINT "UserFlashCardGroup_flashcardgroup_id_fkey";

-- DropIndex
DROP INDEX "UserFlashCard_userflashcardgroup_id_idx";

-- AlterTable
ALTER TABLE "FlashCard" DROP COLUMN "flashcardgroup_id";
ALTER TABLE "FlashCard" ADD COLUMN     "flashcarddeck_id" INT4 NOT NULL;

-- AlterTable
ALTER TABLE "UserFlashCard" DROP COLUMN "userflashcardgroup_id";
ALTER TABLE "UserFlashCard" ADD COLUMN     "priority_num" INT4 NOT NULL;
ALTER TABLE "UserFlashCard" ADD COLUMN     "userflashcarddeck_id" INT4 NOT NULL;

-- DropTable
DROP TABLE "FlashCardGroup";

-- DropTable
DROP TABLE "UserFlashCardGroup";

-- CreateTable
CREATE TABLE "FlashCardDeck" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,

    CONSTRAINT "FlashCardDeck_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserFlashCardDeck" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "flashcarddeck_id" INT4 NOT NULL,
    "graduating_interval" INT4 NOT NULL,
    "easy_interval" INT4 NOT NULL,
    "new_cards_per_day" INT4 NOT NULL,
    "max_reviews_per_day" INT4 NOT NULL,
    "learning_steps" INT8 NOT NULL,

    CONSTRAINT "UserFlashCardDeck_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "UserFlashCardDeck_flashcarddeck_id_idx" ON "UserFlashCardDeck"("flashcarddeck_id");

-- CreateIndex
CREATE INDEX "UserFlashCard_userflashcarddeck_id_idx" ON "UserFlashCard"("userflashcarddeck_id");

-- CreateIndex
CREATE INDEX "UserFlashCard_priority_num_idx" ON "UserFlashCard"("priority_num");

-- CreateIndex
CREATE INDEX "UserFlashCard_priority_num_review_interval_review_factor_idx" ON "UserFlashCard"("priority_num", "review_interval", "review_factor");

-- CreateIndex
CREATE INDEX "UserFlashCard_review_interval_idx" ON "UserFlashCard"("review_interval");

-- CreateIndex
CREATE INDEX "UserFlashCard_review_factor_idx" ON "UserFlashCard"("review_factor");

-- AddForeignKey
ALTER TABLE "FlashCard" ADD CONSTRAINT "FlashCard_flashcarddeck_id_fkey" FOREIGN KEY ("flashcarddeck_id") REFERENCES "FlashCardDeck"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFlashCardDeck" ADD CONSTRAINT "UserFlashCardDeck_flashcarddeck_id_fkey" FOREIGN KEY ("flashcarddeck_id") REFERENCES "FlashCardDeck"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFlashCard" ADD CONSTRAINT "UserFlashCard_userflashcarddeck_id_fkey" FOREIGN KEY ("userflashcarddeck_id") REFERENCES "UserFlashCardDeck"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
